import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, FileCheck2, History, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Shell } from "@/components/shell";
import { Button } from "@/components/ui/button";
import { RedirectToSignIn } from "@/lib/auth/gates";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
import { getQuota, listConversions, type ConversionRow, type Quota } from "@/lib/gst/conversions";

export const Route = createFileRoute("/dashboard")({ component: DashboardPage });

function DashboardPage() {
  const { user, isPending } = useCurrentUserState();
  const [rows, setRows] = useState<ConversionRow[]>([]); const [quota, setQuota] = useState<Quota | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); setError(null); try { const [history, currentQuota] = await Promise.all([listConversions(), getQuota()]); setRows(history); setQuota(currentQuota); } catch (e) { setError(e instanceof Error ? e.message : "Could not load workspace data."); } finally { setLoading(false); } };
  useEffect(() => { if (user) void load(); }, [user]);
  if (isPending) return <Shell><div className="mx-auto max-w-6xl px-4 py-12"><div className="animate-pulse space-y-4"><div className="h-8 w-56 rounded bg-line"/><div className="h-32 rounded-2xl bg-surface"/><div className="h-64 rounded-2xl bg-surface"/></div></div></Shell>;
  if (!user) return <RedirectToSignIn to="/login" />;
  const pct = quota ? Math.min(100, Math.round((quota.used / Math.max(1, quota.limit)) * 100)) : 0;
  const initials = (user.displayName || user.primaryEmail || "G").split(/\s+/).map((x) => x[0]).join("").slice(0, 2).toUpperCase();

  return <Shell><div className="mx-auto max-w-6xl px-4 py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-accent">Workspace</p><h1 className="mt-2 text-4xl tracking-tight">Welcome back, {user.displayName || "there"}.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Fix rejected GST e-invoice JSON, validate safely, and keep your document activity organized.</p></div><div className="flex gap-2"><Link to="/converter"><Button>Fix an invoice <ArrowRight className="ml-2 size-4"/></Button></Link><Button variant="outline" onClick={() => void load()} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</Button></div></div>
    {error ? <div className="mt-5 rounded-xl border border-danger p-4 text-sm text-danger">{error}<button className="ml-2 underline" onClick={() => void load()}>Retry</button></div> : null}
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.55fr_.65fr]">
      <section className="rounded-3xl border border-line bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">Usage this month</p><h2 className="mt-2 text-3xl">{quota?.used ?? "—"} <span className="text-base font-normal text-muted">of {quota?.limit ?? "—"}</span></h2><p className="mt-1 text-sm text-muted">{quota?.remaining ?? "—"} conversions remaining · resets on the 1st</p></div><Link to="/account" className="rounded-full border border-line px-3 py-2 text-xs font-medium hover:border-accent">Account settings</Link></div>{quota ? <><div className="mt-6 h-2.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-accent transition-[width] duration-500" style={{width:`${pct}%`}}/></div><div className="mt-2 flex justify-between text-xs text-muted"><span>{pct}% used</span><span>{quota.planName} · {quota.billingCycle || "monthly"}</span></div></> : null}</section>
      <aside className="rounded-3xl border border-line bg-surface p-5"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-2xl bg-accent text-sm font-semibold text-accent-fg">{initials}</div><div className="min-w-0"><p className="truncate font-medium">{user.displayName || "GST Desk user"}</p><p className="truncate text-xs text-muted">{user.primaryEmail}</p></div></div><div className="mt-5 space-y-2"><Link to="/account" className="flex items-center gap-3 rounded-xl border border-line p-3 text-sm hover:border-accent"><UserRound className="size-4 text-accent"/>Account profile<ArrowRight className="ml-auto size-4"/></Link><div className="flex items-center gap-3 rounded-xl border border-line p-3 text-sm"><ShieldCheck className="size-4 text-accent"/>Secure session<CheckCircle2 className="ml-auto size-4 text-accent"/></div></div></aside>
    </div>
    <section className="mt-5 grid gap-3 sm:grid-cols-3"><Link to="/converter" className="rounded-2xl border border-line bg-surface p-5 transition hover:-translate-y-0.5 hover:border-accent"><FileCheck2 className="size-5 text-accent"/><h3 className="mt-3 font-medium">Fix JSON</h3><p className="mt-1 text-xs leading-5 text-muted">Diagnose, safely fix, validate and download.</p></Link><Link to="/validate" className="rounded-2xl border border-line bg-surface p-5 transition hover:-translate-y-0.5 hover:border-accent"><ShieldCheck className="size-5 text-accent"/><h3 className="mt-3 font-medium">Validate</h3><p className="mt-1 text-xs leading-5 text-muted">Check a payload without changing it.</p></Link><Link to="/bulk" className="rounded-2xl border border-line bg-surface p-5 transition hover:-translate-y-0.5 hover:border-accent"><Sparkles className="size-5 text-accent"/><h3 className="mt-3 font-medium">Bulk tools</h3><p className="mt-1 text-xs leading-5 text-muted">Process multiple JSON files with the same safeguards.</p></Link></section>
    <section className="mt-6 rounded-3xl border border-line bg-surface"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line p-5"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">Activity</p><h2 className="mt-1 text-xl">Recent conversions</h2></div><Link to="/account" className="text-xs font-medium text-accent">Account activity <ArrowRight className="ml-1 inline size-3"/></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-line text-xs uppercase tracking-wide text-muted"><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Supplier</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Total</th><th className="px-5 py-3">Date</th></tr></thead><tbody>{rows.length === 0 ? <tr><td className="px-5 py-10 text-muted" colSpan={5}>No conversions yet. Your corrected-document history will appear here.</td></tr> : rows.map((r) => <tr key={r.id} className="border-b border-line last:border-0"><td className="px-5 py-3 font-mono text-xs">{r.invoiceId}</td><td className="px-5 py-3">{r.supplier || "—"}</td><td className="px-5 py-3">{r.customer || "—"}</td><td className="px-5 py-3">{r.total} {r.currency}</td><td className="px-5 py-3 text-muted">{r.createdAt.slice(0, 10)}</td></tr>)}</tbody></table></div></section>
  </div></Shell>;
}
