import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertCircle, ArrowUpRight, CheckCircle2, Clock3, GitCommitHorizontal, RefreshCw, ShieldAlert } from "lucide-react";
import { Shell } from "@/components/shell";
import { Button } from "@/components/ui/button";
import { RedirectToSignIn } from "@/lib/auth/gates";
import { useCurrentUserState } from "@/lib/auth/use-current-user";

export const Route = createFileRoute("/mission-control")({ component: MissionControlPage });
const ADMIN_EMAIL = "peppolfixbelgium@gmail.com";
const API = "https://api.github.com/repos/peppolfixbelgium-debug/GST-Desk";
const TEAMS = [["Engineering", "Auth, production runtime, security", [1, 3, 17, 22]], ["QA / DQM", "Release evidence and quality gates", [10, 18]], ["R&D", "GST / IRP validation intelligence", [14]], ["Growth", "Acquisition and launch funnel", [12]], ["Stripe", "Billing and entitlements", [19]], ["Legal / GDPR", "Privacy, retention and launch gates", [13]], ["Company / Tax", "Operating readiness", [21]], ["Pricing", "Commercial readiness", [19, 20]]] as const;
type Issue = { number: number; title: string; state: "open" | "closed"; updated_at: string; html_url: string };
type Run = { id: number; name: string; status: string; conclusion: string | null; html_url: string; head_sha?: string; created_at?: string };
type Commit = { sha: string; html_url: string; commit: { message: string; author?: { date?: string } } };
function isAdmin(email: string | null | undefined) { return email?.trim().toLowerCase() === ADMIN_EMAIL; }
async function api<T>(path: string): Promise<T> { const r = await fetch(`${API}${path}`, { headers: { Accept: "application/vnd.github+json" } }); if (!r.ok) throw new Error(`GitHub API ${r.status}`); return r.json() as Promise<T>; }
function age(date?: string) { if (!date) return "—"; const m = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 60000)); return m < 60 ? `${m}m` : m < 1440 ? `${Math.round(m / 60)}h` : `${Math.round(m / 1440)}d`; }
function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Activity }) { return <div className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-wide text-muted">{label}</p><Icon className="size-4 text-muted"/></div><p className="mt-2 text-3xl tracking-tight">{value}</p></div>; }

function MissionControlPage() {
  const { user, isPending } = useCurrentUserState();
  const [issues, setIssues] = useState<Issue[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [commits, setCommits] = useState<Commit[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const refresh = async () => { setLoading(true); setError(null); try { const [i, w, c] = await Promise.all([api<Issue[]>("/issues?state=all&per_page=100"), api<{workflow_runs: Run[]}>("/actions/runs?per_page=12"), api<Commit[]>("/commits?per_page=8")]); setIssues(i.filter((x) => !("pull_request" in x))); setRuns(w.workflow_runs); setCommits(c); } catch (e) { setError(e instanceof Error ? e.message : "Could not load repository state."); } finally { setLoading(false); } };
  useEffect(() => { if (user && isAdmin(user.primaryEmail)) void refresh(); }, [user]);
  const open = useMemo(() => issues.filter((i) => i.state === "open"), [issues]); const closed = useMemo(() => issues.filter((i) => i.state === "closed"), [issues]); const latest = runs[0]; const blockers = open.filter((i) => /P0|BLOCKED|GATE|EXTERNAL/i.test(i.title)); const recent = open.filter((i) => Date.now() - new Date(i.updated_at).getTime() < 48 * 60 * 60 * 1000); const ciHealthy = latest?.conclusion === "success"; const status = latest?.conclusion === "failure" ? "CI needs attention" : blockers.length ? `${blockers.length} release gate${blockers.length === 1 ? "" : "s"} open` : "Release flow healthy";
  if (isPending) return <Shell><div className="mx-auto max-w-6xl px-4 py-12"><div className="animate-pulse space-y-4"><div className="h-8 w-72 rounded bg-line"/><div className="h-28 rounded-2xl bg-surface"/><div className="h-64 rounded-2xl bg-surface"/></div></div></Shell>;
  if (!user) return <RedirectToSignIn to="/login" />;
  if (!isAdmin(user.primaryEmail)) return <Shell><div className="mx-auto max-w-xl px-4 py-20 text-center"><ShieldAlert className="mx-auto size-10 text-danger"/><h1 className="mt-4 text-3xl">Admin access required</h1><p className="mt-2 text-sm text-muted">CEO Command Center is restricted to the founder admin account.</p></div></Shell>;
  return <Shell><div className="mx-auto max-w-6xl px-4 py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-accent">Founder workspace · live repository view</p><h1 className="mt-2 text-4xl tracking-tight">CEO Command Center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">One calm cockpit for execution: what is moving, what is blocked, what CI says, and what the teams have shipped.</p></div><Button variant="outline" onClick={() => void refresh()} disabled={loading}><RefreshCw className={`mr-2 size-4 ${loading ? "animate-spin" : ""}`}/>{loading ? "Refreshing…" : "Refresh"}</Button></div>
    {error ? <div className="mt-5 rounded-xl border border-danger p-4 text-sm text-danger">{error}</div> : null}
    <div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Open work" value={open.length} icon={Clock3}/><Metric label="Moving · 48h" value={recent.length} icon={Activity}/><Metric label="Release gates" value={blockers.length} icon={AlertCircle}/><Metric label="Closed" value={closed.length} icon={CheckCircle2}/></div>
    <section className="mt-5 rounded-2xl border border-line bg-surface p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">Release health</p><h2 className="mt-1 text-2xl">{status}</h2><p className="mt-1 text-sm text-muted">{latest ? `Latest workflow: ${latest.name} · ${age(latest.created_at)} ago` : "Waiting for repository telemetry."}</p></div><div className={`flex items-center gap-2 rounded-full border px-3 py-2 text-xs ${ciHealthy ? "border-accent/40 text-accent" : latest?.conclusion === "failure" ? "border-danger text-danger" : "border-line text-muted"}`}><span className="size-2 rounded-full bg-current"/>{latest?.conclusion ?? latest?.status ?? "unknown"}</div>{latest?.conclusion === "failure" ? <a href={latest.html_url} target="_blank" rel="noreferrer" className="rounded-full border border-danger px-4 py-2 text-xs text-danger">Open failed run <ArrowUpRight className="ml-1 inline size-3"/></a> : null}</div></section>
    <section className="mt-6"><p className="text-xs uppercase tracking-[0.16em] text-muted">Workstreams</p><h2 className="mt-1 text-xl">Team command board</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{TEAMS.map(([name, description, numbers]) => { const mine = issues.filter((i) => numbers.includes(i.number)); const mineOpen = mine.filter((i) => i.state === "open"); const gated = mineOpen.filter((i) => /P0|BLOCKED|GATE|EXTERNAL|production|billing|compliance/i.test(i.title)); const state = gated.length ? "GATED" : mineOpen.length ? "MOVING" : "CLEAR"; return <div key={name} className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-medium">{name}</h3><span className={`text-[10px] font-semibold uppercase tracking-wide ${gated.length ? "text-danger" : mineOpen.length ? "text-accent" : "text-muted"}`}>{state}</span></div><p className="mt-2 min-h-10 text-xs leading-5 text-muted">{description}</p><div className="mt-4 flex items-center justify-between text-xs text-muted"><span>{mineOpen.length} open · {mine.filter((i) => i.state === "closed").length} closed</span>{mineOpen[0] ? <a href={mineOpen[0].html_url} target="_blank" rel="noreferrer" className="text-accent">#{mineOpen[0].number}</a> : null}</div></div>; })}</div></section>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">Execution queue</p><h2 className="mt-1 text-xl">Open issues</h2></div><span className="text-xs text-muted">{open.length}</span></div><div className="mt-4 space-y-2">{open.slice(0, 10).map((i) => <a key={i.number} href={i.html_url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-xl border border-line p-3 hover:border-accent"><div className="min-w-0"><p className="font-mono text-[10px] text-muted">#{i.number}</p><p className="mt-1 truncate text-sm">{i.title}</p></div><span className="shrink-0 text-[10px] text-muted">{age(i.updated_at)}</span></a>)}{!open.length ? <p className="py-8 text-sm text-muted">No open issues.</p> : null}</div></section><section className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">CI pulse</p><h2 className="mt-1 text-xl">Delivery signal</h2></div><span className="text-xs text-muted">{runs.length} runs</span></div><div className="mt-4 space-y-2">{runs.slice(0, 6).map((r) => <a key={r.id} href={r.html_url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-xl border border-line p-3"><span className="min-w-0 truncate text-xs">{r.name}</span><span className={`text-[10px] uppercase ${r.conclusion === "success" ? "text-accent" : r.conclusion === "failure" ? "text-danger" : "text-muted"}`}>{r.conclusion ?? r.status}</span></a>)}</div></section></div>
    <section className="mt-6 rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">Repository activity</p><h2 className="mt-1 text-xl">Recent shipped work</h2></div><GitCommitHorizontal className="size-5 text-muted"/></div><div className="mt-4 grid gap-2 md:grid-cols-2">{commits.map((c) => <a key={c.sha} href={c.html_url} target="_blank" rel="noreferrer" className="rounded-xl border border-line p-3 hover:border-accent"><div className="flex justify-between gap-3"><span className="font-mono text-[10px] text-muted">{c.sha.slice(0,7)}</span><span className="text-[10px] text-muted">{age(c.commit.author?.date)}</span></div><p className="mt-1 truncate text-sm">{c.commit.message.split("\n")[0]}</p></a>)}</div></section>
  </div></Shell>;
}
