import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, AlertCircle, ArrowRight, CheckCircle2, Clock3, GitCommitHorizontal, RefreshCw, ShieldAlert, Target, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Shell } from "@/components/shell";
import { Button } from "@/components/ui/button";
import { RedirectToSignIn } from "@/lib/auth/gates";
import { useCurrentUserState } from "@/lib/auth/use-current-user";

export const Route = createFileRoute("/mission-control")({ component: MissionControlPage });
const ADMIN_EMAIL = "peppolfixbelgium@gmail.com";
const API = "https://api.github.com/repos/peppolfixbelgium-debug/GST-Desk";
const TEAMS = [["Engineering", "Auth, runtime, security", [1, 3, 17, 22]], ["QA / PMO", "Release evidence and quality", [10, 18]], ["R&D", "GST / IRP validation", [14]], ["Growth", "Acquisition and funnel", [12]], ["Billing", "Stripe and entitlements", [19]], ["Legal", "Privacy and launch gates", [13]], ["Company", "Operating readiness", [21]], ["Pricing", "Commercial readiness", [19, 20]]] as const;
type Issue = { number: number; title: string; state: "open" | "closed"; updated_at: string; html_url: string };
type Run = { id: number; name: string; status: string; conclusion: string | null; html_url: string; head_sha?: string; created_at?: string };
type Commit = { sha: string; html_url: string; commit: { message: string; author?: { date?: string } } };
function isAdmin(email: string | null | undefined) { return email?.trim().toLowerCase() === ADMIN_EMAIL; }
async function api<T>(path: string): Promise<T> { const r = await fetch(`${API}${path}`, { headers: { Accept: "application/vnd.github+json" } }); if (!r.ok) throw new Error(`GitHub API ${r.status}`); return r.json() as Promise<T>; }
function age(date?: string) { if (!date) return "—"; const m = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 60000)); return m < 60 ? `${m}m` : m < 1440 ? `${Math.round(m / 60)}h` : `${Math.round(m / 1440)}d`; }
function Metric({ label, value, note, icon: Icon }: { label: string; value: number | string; note: string; icon: typeof Activity }) { return <div className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">{label}</p><Icon className="size-4 text-muted"/></div><p className="mt-3 text-3xl tracking-tight">{value}</p><p className="mt-1 text-xs text-muted">{note}</p></div>; }

function MissionControlPage() {
  const { user, isPending } = useCurrentUserState();
  const [issues, setIssues] = useState<Issue[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [commits, setCommits] = useState<Commit[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const refresh = async () => { setLoading(true); setError(null); try { const [i, w, c] = await Promise.all([api<Issue[]>("/issues?state=all&per_page=100"), api<{workflow_runs: Run[]}>("/actions/runs?per_page=12"), api<Commit[]>("/commits?per_page=8")]); setIssues(i.filter((x) => !("pull_request" in x))); setRuns(w.workflow_runs); setCommits(c); } catch (e) { setError(e instanceof Error ? e.message : "Could not load repository state."); } finally { setLoading(false); } };
  useEffect(() => { if (user && isAdmin(user.primaryEmail)) void refresh(); }, [user]);
  const open = useMemo(() => issues.filter((i) => i.state === "open"), [issues]); const closed = useMemo(() => issues.filter((i) => i.state === "closed"), [issues]); const latest = runs[0]; const blockers = open.filter((i) => /P0|BLOCKED|GATE|EXTERNAL|production|billing|compliance/i.test(i.title)); const recent = open.filter((i) => Date.now() - new Date(i.updated_at).getTime() < 48 * 60 * 60 * 1000); const ciHealthy = latest?.conclusion === "success"; const releaseLabel = latest?.conclusion === "failure" ? "CI needs attention" : blockers.length ? `${blockers.length} release gate${blockers.length === 1 ? "" : "s"} open` : latest?.status === "in_progress" ? "Release in progress" : "Release flow healthy";
  if (isPending) return <Shell><div className="mx-auto max-w-6xl px-4 py-12"><div className="animate-pulse space-y-4"><div className="h-8 w-72 rounded bg-line"/><div className="h-28 rounded-2xl bg-surface"/><div className="h-64 rounded-2xl bg-surface"/></div></div></Shell>;
  if (!user) return <RedirectToSignIn to="/login" />;
  if (!isAdmin(user.primaryEmail)) return <Shell><div className="mx-auto max-w-xl px-4 py-20 text-center"><ShieldAlert className="mx-auto size-10 text-danger"/><h1 className="mt-4 text-3xl">Admin access required</h1><p className="mt-2 text-sm text-muted">The CEO Command Center is restricted to the founder admin account.</p></div></Shell>;
  return <Shell><div className="mx-auto max-w-7xl px-4 py-8 lg:px-6">
    <div className="grid gap-5 lg:grid-cols-[220px_1fr]">
      <aside className="hidden rounded-3xl border border-line bg-surface p-4 lg:block"><div className="px-3 py-2"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-accent">Founder workspace</p><p className="mt-1 text-lg font-semibold">GST Desk</p></div><nav className="mt-5 space-y-1 text-sm"><div className="rounded-xl bg-bg px-3 py-2.5 font-medium">Command Center</div><Link to="/dashboard" className="block rounded-xl px-3 py-2.5 text-muted hover:bg-bg hover:text-fg">Workspace</Link><Link to="/account" className="block rounded-xl px-3 py-2.5 text-muted hover:bg-bg hover:text-fg">Account</Link><Link to="/pricing" className="block rounded-xl px-3 py-2.5 text-muted hover:bg-bg hover:text-fg">Pricing</Link></nav><div className="mt-6 rounded-2xl border border-accent/30 bg-accent/5 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-accent">Live source</p><p className="mt-1 text-xs leading-5 text-muted">Repository issues, Actions and commits refresh directly from GitHub.</p></div></aside>
      <main className="min-w-0">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-accent">Live execution cockpit</p><h1 className="mt-2 text-4xl tracking-tight">CEO Command Center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">A calm, dynamic control room for product execution — what needs attention, what is moving, and what has shipped.</p></div><Button variant="outline" onClick={() => void refresh()} disabled={loading}><RefreshCw className={`mr-2 size-4 ${loading ? "animate-spin" : ""}`}/>{loading ? "Refreshing…" : "Refresh data"}</Button></div>
        {error ? <div className="mt-5 rounded-xl border border-danger p-4 text-sm text-danger">{error}</div> : null}
        <div className="mt-7 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Open work" value={open.length} note="Across the product ledger" icon={Target}/><Metric label="Moving · 48h" value={recent.length} note="Recently updated issues" icon={Activity}/><Metric label="Release gates" value={blockers.length} note="P0 / blocked / external" icon={AlertCircle}/><Metric label="Closed" value={closed.length} note="Completed ledger items" icon={CheckCircle2}/></div>

        <section className="mt-5 rounded-3xl border border-line bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">Release pulse</p><h2 className="mt-2 text-2xl">{releaseLabel}</h2><p className="mt-1 text-sm text-muted">{latest ? `Latest workflow: ${latest.name} · ${age(latest.created_at)} ago` : "Waiting for repository telemetry."}</p></div><div className="flex items-center gap-3"><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs ${ciHealthy ? "border-accent/40 text-accent" : latest?.conclusion === "failure" ? "border-danger text-danger" : "border-line text-muted"}`}><span className="size-2 rounded-full bg-current"/>{latest?.conclusion ?? latest?.status ?? "unknown"}</span>{latest?.conclusion === "failure" ? <a href={latest.html_url} target="_blank" rel="noreferrer" className="text-xs font-medium text-danger">Open failed run <ArrowRight className="ml-1 inline size-3"/></a> : null}</div></div></section>

        <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-3xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">Attention queue</p><h2 className="mt-1 text-xl">What needs attention</h2></div><span className="text-xs text-muted">{open.length} open</span></div><div className="mt-4 space-y-2">{open.slice(0, 8).map((i) => <a key={i.number} href={i.html_url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-2xl border border-line p-3 transition hover:border-accent"><div className={`grid size-8 shrink-0 place-items-center rounded-lg ${/P0|BLOCKED|GATE|EXTERNAL|production|billing|compliance/i.test(i.title) ? "bg-danger/10 text-danger" : "bg-accent/10 text-accent"}`}><Zap className="size-4"/></div><div className="min-w-0 flex-1"><p className="font-mono text-[10px] text-muted">#{i.number}</p><p className="mt-0.5 truncate text-sm">{i.title}</p></div><span className="shrink-0 text-[10px] text-muted">{age(i.updated_at)}</span></a>)}{!open.length ? <p className="py-8 text-sm text-muted">No open issues.</p> : null}</div></section><section className="rounded-3xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">Delivery signal</p><h2 className="mt-1 text-xl">CI pulse</h2></div><span className="text-xs text-muted">{runs.length} recent runs</span></div><div className="mt-4 space-y-2">{runs.slice(0, 7).map((r) => <a key={r.id} href={r.html_url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-2xl border border-line p-3 hover:border-accent"><span className="min-w-0 truncate text-xs">{r.name}</span><span className={`shrink-0 text-[10px] uppercase ${r.conclusion === "success" ? "text-accent" : r.conclusion === "failure" ? "text-danger" : "text-muted"}`}>{r.conclusion ?? r.status}</span></a>)}</div></section></div>

        <section className="mt-5"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">Operating map</p><h2 className="mt-1 text-xl">Team pulse</h2></div><p className="text-xs text-muted">Derived from live issue state</p></div><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{TEAMS.map(([name, description, numbers]) => { const mine = issues.filter((i) => numbers.includes(i.number)); const mineOpen = mine.filter((i) => i.state === "open"); const gated = mineOpen.filter((i) => /P0|BLOCKED|GATE|EXTERNAL|production|billing|compliance/i.test(i.title)); const state = gated.length ? "GATED" : mineOpen.length ? "MOVING" : "CLEAR"; return <div key={name} className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-medium">{name}</h3><span className={`text-[10px] font-semibold tracking-wide ${gated.length ? "text-danger" : mineOpen.length ? "text-accent" : "text-muted"}`}>{state}</span></div><p className="mt-2 min-h-10 text-xs leading-5 text-muted">{description}</p><div className="mt-4 flex items-center justify-between text-xs text-muted"><span>{mineOpen.length} open · {mine.filter((i) => i.state === "closed").length} closed</span>{mineOpen[0] ? <a href={mineOpen[0].html_url} target="_blank" rel="noreferrer" className="text-accent">#{mineOpen[0].number}</a> : null}</div></div>; })}</div></section>

        <section className="mt-5 rounded-3xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-muted">Repository activity</p><h2 className="mt-1 text-xl">Recently shipped</h2></div><GitCommitHorizontal className="size-5 text-muted"/></div><div className="mt-4 grid gap-2 md:grid-cols-2">{commits.map((c) => <a key={c.sha} href={c.html_url} target="_blank" rel="noreferrer" className="rounded-2xl border border-line p-3 hover:border-accent"><div className="flex justify-between gap-3"><span className="font-mono text-[10px] text-muted">{c.sha.slice(0,7)}</span><span className="text-[10px] text-muted">{age(c.commit.author?.date)}</span></div><p className="mt-1 truncate text-sm">{c.commit.message.split("\n")[0]}</p></a>)}</div></section>
      </main>
    </div>
  </div></Shell>;
}
