export const PRICING = [
  {
    id: "free",
    name: "Free",
    price: 0,
    invoices: 5,
    blurb: "For a practice testing real IRP JSON.",
    features: ["5 invoices / calendar month", "Supported IRP error mapping", "HSN + PIN auto-fix", "EN / हिन्दी"],
    cta: "Start free",
  },
  {
    id: "starter",
    name: "CA Starter",
    price: 999,
    invoices: 100,
    blurb: "Solo CAs clearing portal rejections.",
    features: ["100 invoices / month", "Bulk ZIP", "History", "Email support"],
    cta: "Choose Starter",
  },
  {
    id: "firm",
    name: "Firm",
    price: 2499,
    invoices: 400,
    blurb: "The busy CA firm plan.",
    features: ["400 invoices / month", "Bulk ZIP", "Priority support", "Team history"],
    cta: "Choose Firm",
    popular: true,
  },
  {
    id: "practice",
    name: "Practice",
    price: 4999,
    invoices: 1500,
    blurb: "For higher-volume validation workflows.",
    features: ["1,500 invoices / month", "Bulk ZIP", "Named contact", "SLA on request"],
    cta: "Choose Practice",
  },
] as const;
