/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ValidateRouteImport } from './routes/validate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GstEInvoiceErrors2176RouteImport } from './routes/gst-e-invoice-errors/2176'
import { Route as GstEInvoiceErrors2189RouteImport } from './routes/gst-e-invoice-errors/2189'
import { Route as GstEInvoiceErrors3039RouteImport } from './routes/gst-e-invoice-errors/3039'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateRoute = ValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GstEInvoiceErrors2176Route = GstEInvoiceErrors2176RouteImport.update({
  id: '/gst-e-invoice-errors/2176',
  path: '/gst-e-invoice-errors/2176',
  getParentRoute: () => rootRouteImport,
} as any)
const GstEInvoiceErrors2189Route = GstEInvoiceErrors2189RouteImport.update({
  id: '/gst-e-invoice-errors/2189',
  path: '/gst-e-invoice-errors/2189',
  getParentRoute: () => rootRouteImport,
} as any)
const GstEInvoiceErrors3039Route = GstEInvoiceErrors3039RouteImport.update({
  id: '/gst-e-invoice-errors/3039',
  path: '/gst-e-invoice-errors/3039',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mission-control': typeof MissionControlRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/validate': typeof ValidateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/gst-e-invoice-errors/2176': typeof GstEInvoiceErrors2176Route
  '/gst-e-invoice-errors/2189': typeof GstEInvoiceErrors2189Route
  '/gst-e-invoice-errors/3039': typeof GstEInvoiceErrors3039Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mission-control': typeof MissionControlRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/validate': typeof ValidateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/gst-e-invoice-errors/2176': typeof GstEInvoiceErrors2176Route
  '/gst-e-invoice-errors/2189': typeof GstEInvoiceErrors2189Route
  '/gst-e-invoice-errors/3039': typeof GstEInvoiceErrors3039Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mission-control': typeof MissionControlRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/validate': typeof ValidateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/gst-e-invoice-errors/2176': typeof GstEInvoiceErrors2176Route
  '/gst-e-invoice-errors/2189': typeof GstEInvoiceErrors2189Route
  '/gst-e-invoice-errors/3039': typeof GstEInvoiceErrors3039Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/converter'
    | '/dashboard'
    | '/login'
    | '/mission-control'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/validate'
    | '/api/auth/$'
    | '/gst-e-invoice-errors/2176'
    | '/gst-e-invoice-errors/2189'
    | '/gst-e-invoice-errors/3039'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/converter'
    | '/dashboard'
    | '/login'
    | '/mission-control'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/validate'
    | '/api/auth/$'
    | '/gst-e-invoice-errors/2176'
    | '/gst-e-invoice-errors/2189'
    | '/gst-e-invoice-errors/3039'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/converter'
    | '/dashboard'
    | '/login'
    | '/mission-control'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/validate'
    | '/api/auth/$'
    | '/gst-e-invoice-errors/2176'
    | '/gst-e-invoice-errors/2189'
    | '/gst-e-invoice-errors/3039'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  ConverterRoute: typeof ConverterRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MissionControlRoute: typeof MissionControlRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  ValidateRoute: typeof ValidateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GstEInvoiceErrors2176Route: typeof GstEInvoiceErrors2176Route
  GstEInvoiceErrors2189Route: typeof GstEInvoiceErrors2189Route
  GstEInvoiceErrors3039Route: typeof GstEInvoiceErrors3039Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-e-invoice-errors/2176': {
      id: '/gst-e-invoice-errors/2176'
      path: '/gst-e-invoice-errors/2176'
      fullPath: '/gst-e-invoice-errors/2176'
      preLoaderRoute: typeof GstEInvoiceErrors2176RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-e-invoice-errors/2189': {
      id: '/gst-e-invoice-errors/2189'
      path: '/gst-e-invoice-errors/2189'
      fullPath: '/gst-e-invoice-errors/2189'
      preLoaderRoute: typeof GstEInvoiceErrors2189RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-e-invoice-errors/3039': {
      id: '/gst-e-invoice-errors/3039'
      path: '/gst-e-invoice-errors/3039'
      fullPath: '/gst-e-invoice-errors/3039'
      preLoaderRoute: typeof GstEInvoiceErrors3039RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  ConverterRoute: ConverterRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MissionControlRoute: MissionControlRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  ValidateRoute: ValidateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GstEInvoiceErrors2176Route: GstEInvoiceErrors2176Route,
  GstEInvoiceErrors2189Route: GstEInvoiceErrors2189Route,
  GstEInvoiceErrors3039Route: GstEInvoiceErrors3039Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
